### ISSUE TITLE
Is the instrumented binary mandatory

### ISSUE THREAD

**Issue by superirishdonkey** [floyd-fuh/afl-crash-analyzer#2]
Hi, 

Is the "target_binary_instrumented" mandatory for afl-crash-analyzer? because I don't have source code for the binary, so I have no instrumented binary.
I guess this project only works for the analyzing the crash that source code available, correct?

Thanks
Michael

**Comment by floyd-fuh** [comment]
This project was developed for AFL generated crashes. You don't need the source code, but you need an AFL instrumented binary. This means you could use afl-dyninst to get an instrumented binary.

Mainly you won't be able to use afl-tmin to minimize crashes. However, you could easily use the old tmin by Michal instead: http://lcamtuf.coredump.cx/soft/tmin.tgz . So yeah, you can use this project without an instrumented binary, but it needs some changes.

There are actually only very few instances where the instrumented binary is used: https://github.com/floyd-fuh/afl-crash-analyzer/search?utf8=%E2%9C%93&q=%22target_binary_instrumented%22&type=Code
